#%RAML 1.0 ResourceType

description: A single entity of a resource
usage: Use this to describe resource represents a single entity

uses:
  odata: !include ../libraries/odataAnnotations.raml
is: [odata.filter, odata.expand, odata.format, odata.select]
get:
  description: Read <<model>>
  responses:
    200:
      body:
        application/json:
          type: <<model>>
delete:
  description: Delete <<model>>
  responses:
    200:
      body:
        application/json:
          type: <<model>>
put:
  description: Update <<model>>
  body:
    application/json:
      type: <<model>>
  responses:
    204:
      body:
        application/json:
          type: <<model>>