enableAllureTestReportStage: false
mavenSettingsXmlId: ab7820eb-e393-4e88-9962-92104044ed75
projectType: extension
additionalTestConfigs:
  jdk17-4.9.x:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -DruntimeVersion=4.9.0 -DruntimeProduct=MULE_EE
