#%RAML 1.0 Library
usage: |
  Use to define an OData Entity Model
uses:
  odata: odataLibrary.raml

types:
  odataTypes:
    (odata.remote): odataTypes
    properties:
      edmString:
        type: string
        (odata.key): false
        (odata.nullable): false
      edmBoolean:
        type: boolean
        (odata.key): false
        (odata.nullable): false
      edmDouble:
        type: number
        (odata.key): false
        (odata.nullable): false
      edmSingle:
        type: number
        (odata.key): false
        (odata.nullable): false
        format: float
      edmBinary:
        type: file
        (odata.key): false
        (odata.nullable): false
      edmDateTime:
        type: datetime-only
        (odata.key): false
        (odata.nullable): false
      edmInt32:
        type: integer
        (odata.key): false
        (odata.nullable): false
      edmInt64:
        type: integer
        (odata.key): false
        (odata.nullable): false
        format: int64
      edmInt16:
        type: integer
        (odata.key): false
        (odata.nullable): false
        format: int16
      edmByte:
        type: integer
        (odata.key): false
        (odata.nullable): false
        format: int8
      edmDecimal:
        type: number
        (odata.key): false
        (odata.nullable): false
        (odata.precision): 3
        (odata.scale): 3
      edmGuid:
        type: string
        (odata.key): false
        (odata.nullable): false
        (odata.type): guid
      edmTime:
        type: time-only
        (odata.key): false
        (odata.nullable): false
      edmDateTimeOffset:
        type: datetime
        (odata.key): false
        (odata.nullable): false