#%RAML 1.0 Library
uses:
  odata: !include libraries/odata.raml

typesss:
  MyEntity:
    properties:
      MyField:
        type: decimal
        (odata.key): true
		(odata.nullable): false,
		(odata.precision): 2,
		(odata.scale): 2
        