#%RAML 1.0 Library
uses:
  odata: libraries/odata.raml

types:
  Employee:
    (odata.remote): myEntity
    properties:
      id:
        type: decimal
        (odata.key): true
        (odata.nullable): false
      name:
        type: string
        (odata.key): false
        (odata.nullable): false
      age:
        type: integer
        (odata.key): false
        (odata.nullable): false
  Customer:
    (odata.remote): myEntity
    properties:
      id:
        type: decimal
        (odata.key): true
        (odata.nullable): false
      name:
        type: string
        (odata.key): false
        (odata.nullable): false    
      address:
        type: string
        (odata.key): false
        (odata.nullable): false 