#%RAML 1.0 Library
uses:
  odata: libraries/odataLibrary.raml

types:
  Employee:
    properties:
      id:
        type: integer
        (odata.key): true
        (odata.nullable): false
      name:
        type: string
        (odata.nullable): false
        (odata.key): false
        maxLength: 2        
      age:
        type: integer
        (odata.nullable): true
        (odata.key): false