#%RAML 1.0 Library
uses:
  odata: libraries/odataLibrary.raml

types:
  MyEntity:
    (odata.remote): myEntity 
    properties:
      MyField:
        type: number
        (odata.key): false
        (odata.nullable): false
        (odata.precision): 2
        (odata.scale): 2
        