#%RAML 1.0 Library
uses:
  odata: libraries/odataLibrary.raml
types:
  tickets:
    (odata.remote): Tickets
    properties:
      TicketID:
        type: integer
        (odata.key): true
        (odata.nullable): false
      TicketName:
        type: string
        (odata.nullable): false
        (odata.key): false
        maxLength: 10